### ISSUE TITLE
EVA Construction: Placing a scaled part on the ground or anywhere on the vessel, then picking it back up...

### ISSUE THREAD

**Issue by numberlesstim** [JonnyOThan/TweakScale#44]
...changes the attach nodes to what looks like the default scaled part positions. They now stay like that even after attaching back onto the vessel.

![EVA](https://github.com/JonnyOThan/TweakScale/assets/117858473/8f8b20cb-5862-4182-8735-6da116d56eb4)

**Comment by JonnyOThan** [comment]
Can you give solid repro steps for eva construction bugs?  And indicate whether the ship was newly launched or loaded from a save? Note revert to launch is loading from a save.

**Comment by numberlesstim** [comment]
This one was a new launch, cheated to minmus for part weight reasons

**Comment by numberlesstim** [comment]
[eva construction.zip](https://github.com/JonnyOThan/TweakScale/files/14072869/eva.construction.zip)

Only happens on a new launch, not after revert.
Go eva -> pick up part -> place on ground -> pick back up -> AttachNodes are wrong

**Comment by numberlesstim** [comment]
Also save + reload after AttachNodes are bad will fix them when next time moving them in EVAConstruciton mode.

**Comment by JonnyOThan** [comment]
OK, sort of sounds at least close enough to #42
