### ISSUE TITLE
Dockingports dont always scale correctly with the Match Node feature

### ISSUE THREAD

**Issue by numberlesstim** [JonnyOThan/TweakScale#47]
All ports: 0.938m
Junior: All sizes except 0.625m and 3.75m

![Ports](https://github.com/JonnyOThan/TweakScale/assets/117858473/e71ea543-9f65-4d06-bd14-b612575f7fe1)

**Comment by JonnyOThan** [comment]
Probably some kind of floating point precision issue matching the multiplied scale to the named scale values.

**Comment by JonnyOThan** [comment]
0.9375 being missing is by design - the given sizes match well established names for docking port diameters.  I'm not sure if there's one for 0.9375.
