### ISSUE TITLE
FreeIva: Docking two ports of different nodetypes will have hatches either blocked or lead to EVA

### ISSUE THREAD

**Issue by numberlesstim** [JonnyOThan/TweakScale#48]

**Comment by JonnyOThan** [comment]
Can you provide a craft or save file that has this issue?

**Comment by numberlesstim** [comment]
Huh, i can no longer reproduce this.
I reinstalled the mod in the meantime, maybe that fixed things?
Both times v3.1.3, but for the earlier times i did only overwrite the old version, now i am running a clean install...

I did use a setup similar to this one:
[docking.zip](https://github.com/JonnyOThan/TweakScale/files/14072774/docking.zip)

**Comment by JonnyOThan** [comment]
I wouldn't be surprised if there's some very specific steps that will reproduce it, maybe differing between launching the ship from VAB vs loading a save.

**Comment by JonnyOThan** [comment]
Please comment if you see it again.
