### ISSUE TITLE
Scaling changes behaviour after re-rooting

### ISSUE THREAD

**Issue by numberlesstim** [JonnyOThan/TweakScale#54]
After re-rooting some parts will no longer scale around the right point:

Before re-rooting:
![before_re_root](https://github.com/JonnyOThan/TweakScale/assets/117858473/142e02b8-c145-4287-904f-3fcd7858d3e5)
After re-rooting:
![after_re_root](https://github.com/JonnyOThan/TweakScale/assets/117858473/d982ab4a-a353-4a06-be5b-cd4ae089f917)

Steps to reproduce:
[ReRootScalingTool.zip](https://github.com/JonnyOThan/TweakScale/files/14155831/ReRootScalingTool.zip)

1. Load the above craft, or place a Mk1-cockpit with 2 fuel tanks attached.
2. Make sure 'scale children' option is enabled.
3. Select the scaling tool on the cockpit and drag on the arrows
4. Observe the craft scaling correctly
5. Re-root to the second tank, then back to the cockpit.
6. Repeat step 3.
7. Observe the craft no longer scaling correctly

This happens with all the possible ways to rescale:

- Scaling tool --> click cockpit --> drag arrows
- Cockpit paw --> click on 'scale up' or 'scale down' button
- Cockpit paw --> click somewhere on the 'scaling bar'

**Comment by JonnyOThan** [comment]
Repro actually seems simpler:

1. Place a cockpit and a fuel tank under it
2. re-root to the fuel tank
3. start scaling with "scale children" enabled
