### ISSUE TITLE
Conflict with Tundra Exploration interstage

### ISSUE THREAD

**Issue by Sanchez-1** [JonnyOThan/TweakScale#66]
### What did you do before the bug occurred?

I right clicked on to the Falcon 9 interstage. All of the other parts don't have any issue.

### What happened?

I wanted to change one of the logos on the interstage and was met with the PAW killing itself completely.

_I can confirm that Tweakscale is some how involved, either via the conflict with TE or with another mod just unsure._

### Upload your ksp.log file

[Had to upload it to google drive.](https://drive.google.com/file/d/1ya9PVhXLG2DCNhVLMfQAPjlpkjuI9NBp/view?usp=sharing)

### A screenshot of the problem

![image](https://github.com/JonnyOThan/TweakScale/assets/47197301/696748d3-2725-40ac-9a81-c92c3e7f817b)

You can see the PAW to the left of the screenshot.

**Comment by JonnyOThan** [comment]
[tweakscale-#66.zip](https://github.com/JonnyOThan/TweakScale/files/14667348/tweakscale-.66.zip)

adding log file in case the original is deleted

**Comment by JonnyOThan** [comment]
Confirmed.

**Comment by Sanchez-1** [comment]
May I ask when the next release is planned for?

**Comment by JonnyOThan** [comment]
There's no set date but I hope to have it out within a few days.
