### ISSUE TITLE
Report: node positions are incorrect if the default b9ps subtype moves them

### ISSUE THREAD

**Issue by PointBlank66** [JonnyOThan/TweakScale#70]
### What did you do before the bug occurred?

I was busy getting a new RSS installment ready.
I started with installing RSS, LRTR and its dependencies, along side the visual stuff (PRVE 64K, Parallex, Scatterer, etc)
Also installed a couple of part mods, most notably Habtech, as I use that the most for designing orbital stations

### What happened?

after installing the above mentioned mods I loaded up the game and did a preliminary test to see if everything was installed correctly and loaded in as it should in the VAB and SPH. There I noticed that some parts had misaligned attachment nodes. In the screenshot provided below I show an example with Habtech's Scientific Experiment Platform of what's going on.

### Upload your ksp.log file

[KSP.log](https://github.com/JonnyOThan/TweakScale/files/15154527/KSP.log)

### A screenshot of the problem

With Tweakscale ![image](https://github.com/JonnyOThan/TweakScale/assets/4239471/fc766a40-c2d2-49d9-8508-b58dace6c4e8)
Without Tweakscale ![image](https://github.com/JonnyOThan/TweakScale/assets/4239471/faa827c8-cb7c-428a-9383-8316bc9ad0ab)
Mods that I have installed at the time of finding the bug 
![image](https://github.com/JonnyOThan/TweakScale/assets/4239471/0c0eae1b-6033-461f-9bf1-bc881158d8ca)

**Comment by JonnyOThan** [comment]
Hi @PointBlank66 , your log file shows that tweakscale is not installed. In order for it to be useful, I need to see the log file from when the problem occurred.

**Comment by PointBlank66** [comment]
[KSP.log](https://github.com/JonnyOThan/TweakScale/files/15162944/KSP.log)

**Comment by JonnyOThan** [comment]
Possibly the same as this report: https://discord.com/channels/206181796164009984/1179119373022150686/1260520390778814585
